excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://shileyhinton.github.io
title: WELCOME TO THE SANGHA
tagline: The path to Nirvana.
description:  Welcome to the glamorous way of Zen! In its largest sense, all living beings make up our family, though when commonly used Sangha means our fellows in the local zen center or the group in our area with whom we practice. With this blog, we will follow the Eight-fold Path and practice healthy lifestyle practices, focus on channeling negative energy into positive energy, and use the moon cycle for guiding our meditation.
paginate: 5